SUBJECTS = {
    "AA": "📐 Mathematik",
    "GEOM": "📐 Geometrie",
    "D": "📖 Deutsch",
    "E": "🇬🇧 Englisch",
    "I": "🇮🇹 Italienisch",
    "BG": "🎨 Bildnerisches Gestalten",
    "GG": "🌍 Geografie",
    "G": "🏰 Geschichte",
    "MU": "🎵 Musik",
    "NL": "🧪 Naturlehre",
    "REL": "⛪ Religion",
    "MICT": "💻 Medien & Informatik",
    "TGWE": "🛠️ Gestalten",
    "KLST": "👥 Klassenstunde",
    "SMD": "🏃 Sport",
}